import type { Manual } from "@/dominio/tipos";

export const manuais: Manual[] = [
  {
    id: "m-1",
    nome: "Emitir nota fiscal de serviço",
    sistema: "ERP Acme",
    urlSistema: "https://erp.acme.internal",
    projeto: "Financeiro",
    status: "publicado",
    modo: "extensao",
    passos: 14,
    atualizadoEm: "2026-09-08",
  },
  {
    id: "m-2",
    nome: "Cadastrar novo colaborador",
    sistema: "Portal RH",
    urlSistema: "https://rh.acme.internal",
    projeto: "RH e admissão",
    status: "em_revisao",
    modo: "extensao",
    passos: 9,
    atualizadoEm: "2026-09-09",
  },
  {
    id: "m-3",
    nome: "Abrir chamado de infraestrutura",
    sistema: "Central de Suporte",
    urlSistema: "https://suporte.acme.internal",
    projeto: "Suporte interno",
    status: "em_captura",
    modo: "embed",
    passos: 6,
    atualizadoEm: "2026-09-10",
  },
  {
    id: "m-4",
    nome: "Aprovar reembolso de despesa",
    sistema: "ERP Acme",
    urlSistema: "https://erp.acme.internal",
    projeto: "Financeiro",
    status: "rascunho",
    modo: "extensao",
    passos: 0,
    atualizadoEm: "2026-09-05",
  },
  {
    id: "m-5",
    nome: "Configurar assinatura de e-mail",
    sistema: "Workspace",
    urlSistema: "https://mail.acme.internal",
    projeto: "Onboarding de clientes",
    status: "publicado",
    modo: "embed",
    passos: 5,
    atualizadoEm: "2026-08-30",
  },
];
